<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageFrame</name>
   <tag></tag>
   <elementGuidId>6ce3cac7-111e-4841-bf0d-dd4d3424e4ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageFrame&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>45230c9d-75c0-46ce-8789-4db0a672f84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>allclasses-frame.html</value>
      <webElementGuid>745fae92-e6ee-4ad1-bec8-180c89856eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>eab5c31e-8e8c-431b-8f9d-1ce818519279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All classes and interfaces (except non-static nested types)</value>
      <webElementGuid>d99e9a22-577a-4ee7-bd50-ee193b388c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftBottom&quot;]/iframe[1]</value>
      <webElementGuid>64c58b7a-f62e-4a3c-bcf2-d18e06d2d532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>60acfb28-3077-491e-a012-e1086129418d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>allclasses-frame.html</value>
      <webElementGuid>ebb9e9f4-feab-4237-ad19-2034e95baa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageFrame</value>
      <webElementGuid>88002bc7-ee05-4e48-ad06-97e818937002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All classes and interfaces (except non-static nested types)</value>
      <webElementGuid>bd0edfb1-9326-43ff-a603-0eab43544969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftBottom&quot;]/iframe[1]</value>
      <webElementGuid>6c486e1a-b550-408e-a636-d0f9a59d09d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageFrame']</value>
      <webElementGuid>a26da036-79fa-4e5f-a8eb-c9506d2c7a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/iframe</value>
      <webElementGuid>6b6d779b-a7b1-470f-9ac9-b06eba4e5533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'allclasses-frame.html' and @name = 'packageFrame' and @title = 'All classes and interfaces (except non-static nested types)']</value>
      <webElementGuid>f34f2377-cc33-4027-9a4a-6e3228d6c67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
