<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c0840494-52eb-4523-b098-5d381a003662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard-quick-launch-panel-menu_holder']/table/tbody/tr/td[4]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68000689-227f-4963-9cf1-dd15fb5cf006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_62f36c8c0bead0.07181735/orangehrmLeavePlugin/images/ApplyLeave.png</value>
      <webElementGuid>4f50f255-2efc-4438-b1ba-4a98f80e250a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-quick-launch-panel-menu_holder&quot;)/table[@class=&quot;quickLaungeContainer&quot;]/tbody[1]/tr[1]/td[4]/div[@class=&quot;quickLaunge&quot;]/a[1]/img[1]</value>
      <webElementGuid>7d0b7c37-9529-43e4-a9dc-168650b7c8c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-quick-launch-panel-menu_holder']/table/tbody/tr/td[4]/div/a/img</value>
      <webElementGuid>4efb9005-364b-460a-9861-79a3618cd928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a/img</value>
      <webElementGuid>7f804528-5c5f-4098-baf8-eea56bf37f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_62f36c8c0bead0.07181735/orangehrmLeavePlugin/images/ApplyLeave.png']</value>
      <webElementGuid>5df450d4-caff-4729-80f8-2992b0ec6425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
