<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status__search</name>
   <tag></tag>
   <elementGuidId>cab3e9f4-2721-46ae-bb3c-f88b0202d374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>634a532a-85bf-42e0-b9a1-0ea9a1b88d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>495e0bcc-00cd-44ea-b472-e24ba5fa8381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchbutton hover</value>
      <webElementGuid>4eb35d41-bb1e-4228-8fc4-1860bbbc79c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBtn</value>
      <webElementGuid>0dbc4a4e-b0bb-41e8-a8cf-2be11f30a01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d7a4d3ce-8844-48a9-b2ec-93eefc870292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_search</value>
      <webElementGuid>876d5170-4ee4-4af2-931f-e2b974b55bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBtn&quot;)</value>
      <webElementGuid>75626f92-44b5-42ce-b1db-f17da546bba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBtn']</value>
      <webElementGuid>c8fd5b93-4638-4595-9595-de5c1fac51b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/p/input</value>
      <webElementGuid>2e1944ea-c7d4-4255-9eb9-b316f58fb666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>6cc11585-5796-4f88-b4bf-107e2c11e768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'searchBtn' and @name = '_search']</value>
      <webElementGuid>e29d1cb5-931e-412a-bee7-8087f439b4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
