<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_searchSystemUseremploye_55f714</name>
   <tag></tag>
   <elementGuidId>d9e32bde-1b68-4f8f-9f90-2c149d85470b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchSystemUser_employeeName_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchSystemUser_employeeName_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>babd4ce6-763e-4c7d-b3fe-a3bb1c64b930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>404cb3e8-93bf-42d3-97b5-f6f160cf3928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSystemUser[employeeName][empName]</value>
      <webElementGuid>00490c70-904f-4132-9aa0-40e1eb943ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSystemUser_employeeName_empName</value>
      <webElementGuid>873ff781-8028-48de-a20b-2cebf855f63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>7bfdc9ae-cd7f-4b7a-8e37-c074611b867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f2430824-9828-4eb4-912b-89e5ed735cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSystemUser_employeeName_empName&quot;)</value>
      <webElementGuid>de34f0d3-ff4b-4f37-a9b2-1b5e5795d7fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchSystemUser_employeeName_empName']</value>
      <webElementGuid>5112e5a3-85f1-4f7b-af87-1012b1eafe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li[3]/input</value>
      <webElementGuid>757660e5-ebe4-4775-9b6a-72651017a8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>8b7b5aa1-576d-4d42-9ddb-997723234200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchSystemUser[employeeName][empName]' and @id = 'searchSystemUser_employeeName_empName']</value>
      <webElementGuid>ad992ced-d006-4610-937e-3c5d9b599fac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
